### ISSUE TITLE
https://github.com/radekg/terraform-provisioner-ansible archived?

### ISSUE THREAD

**Issue by nemonik** [radekg/radekg.github.com#4]
Was this intentional?  

Are you abandoning the terraform-provisioner-ansible plugin?

**Comment by radekg** [comment]
Hi @nemonik. It was intentional. I have no capacity to run this project anymore.

**Comment by nemonik** [comment]
A whole team of people have appreciated your work for around 2 years now.  Thank you.

**Comment by radekg** [comment]
Thanks for a good word.
